springdoc.packages-to-scan=utng.edu.mx.prueba
server.port=8035
spring.application.name=utng-prueba
spring.cloud.config.import-check.enabled=false
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# Configuración de la base de datos PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Configuración de Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.entity-scan.base-packages=utng.edu.mx.prueba.entity.empresa

# ? Configuración del Keystore
app.cryto.validafirma.file=C:/keys/miKeystore.jks
app.cryto.validafirma.password=123456

spring.jackson.deserialization.fail-on-invalid-subtype=true
spring.jackson.deserialization.fail-on-numbers-for-enums=true

# PayPal Config
paypal.client.id=AeasiPr49qo85Vy_PxC65D6cjCZJwhdRalU02Ng63GL9tr_afzulw_kSKjTMZDWIhJe1Tu5F4ffL5s9v
paypal.client.secret= EAHqcsfkavrUfbHfnb7RLAd4WtfGUd0Q4F-EovI5-1NbzliyOqs6fhjAW2YS0wW6yLgrauesnzJz3X7r
paypal.api.base-url=https://api.sandbox.paypal.com
